// <auto-generated/>
#nullable enable annotations
#nullable disable warnings
#pragma warning disable

namespace System.Runtime.CompilerServices
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace ValveKeyValue.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    file static class KVSerializerInterceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYVYLAABQcm9ncmFtLmNz")] // Program.cs(143,61)
        public static global::Sample.Account Deserialize_Sample_Account(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Account>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Account, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYQ8NAABQcm9ncmFtLmNz")] // Program.cs(151,69)
        public static global::Sample.ByReference Deserialize_Sample_ByReference(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.ByReference>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_ByReference, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYcILAABQcm9ncmFtLmNz")] // Program.cs(145,67)
        public static global::Sample.Configured Deserialize_Sample_Configured(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Configured>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Configured, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYSsMAABQcm9ncmFtLmNz")] // Program.cs(147,61)
        public static global::Sample.Factory Deserialize_Sample_Factory(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Factory>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Factory, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYZgMAABQcm9ncmFtLmNz")] // Program.cs(149,68)
        public static global::Sample.Outer<int>.Inner Deserialize_Sample_Outer_1int_2_Inner(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Outer<int>.Inner>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Outer_1int_2_Inner, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYWoKAABQcm9ncmFtLmNz")] // Program.cs(139,63)
        public static global::Sample.Pair<string> Deserialize_Sample_Pair_1string_2(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Pair<string>>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Pair_1string_2, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYQQKAABQcm9ncmFtLmNz")] // Program.cs(137,57)
        public static global::Sample.Point Deserialize_Sample_Point(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Point>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Point, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYXAOAABQcm9ncmFtLmNz")] // Program.cs(157,77)
        public static global::Sample.SpanConstructor Deserialize_Sample_SpanConstructor(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.SpanConstructor>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_SpanConstructor, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYX0NAABQcm9ncmFtLmNz")] // Program.cs(153,65)
        public static global::Sample.TwoMarked Deserialize_Sample_TwoMarked(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.TwoMarked>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_TwoMarked, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYe0OAABQcm9ncmFtLmNz")] // Program.cs(159,76)
        public static global::System.Collections.Generic.Dictionary<global::Sample.Point, int> Deserialize_System_Collections_Generic_Dictionary_1Sample_Point_3int_2(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::System.Collections.Generic.Dictionary<global::Sample.Point, int>>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.System_Collections_Generic_Dictionary_1Sample_Point_3int_2, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYdsKAABQcm9ncmFtLmNz")] // Program.cs(141,67)
        public static global::System.ValueTuple<global::Sample.Size, global::Sample.Counter> Deserialize_System_ValueTuple_1Sample_Size_3Sample_Counter_2(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.System_ValueTuple_1Sample_Size_3Sample_Counter_2, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYfUNAABQcm9ncmFtLmNz")] // Program.cs(155,77)
        public static void Serialize_Sample_Ambiguous(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::Sample.Ambiguous data, string name, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Serialize<global::Sample.Ambiguous>(stream, data, name, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Ambiguous, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYVgPAABQcm9ncmFtLmNz")] // Program.cs(161,51)
        public static (string Text, global::System.Collections.Generic.IReadOnlyList<global::ValveKeyValue.KvSourceSpan> Spans) SerializeWithSourceMap_Sample_Point(this global::ValveKeyValue.KVSerializer serializer, global::Sample.Point data, string name, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.SerializeWithSourceMap<global::Sample.Point>(data, name, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Point, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYcoPAABQcm9ncmFtLmNz")] // Program.cs(163,56)
        public static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Point> GetTypeInfo_Sample_Point()
            => global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Point;

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "btDTkMKzJw433+uglNnrYSEQAABQcm9ncmFtLmNz")] // Program.cs(165,52)
        public static global::ValveKeyValue.Metadata.KVTypeInfo<int> GetTypeInfo_int()
            => global::ValveKeyValue.Metadata.KVMetadata.Int32;
    }
}
