// <auto-generated/>
#nullable enable annotations
#nullable disable warnings
#pragma warning disable

namespace ValveKeyValue.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class KVGeneratedTypeInfo__For_Sample_DCF88FC7
    {
        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Account>? _Sample_Account;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Account> Sample_Account => _Sample_Account ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Account>(
            create: static _ => Create_Account(),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Account>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Account, string>("Id", "Id", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Account t) => t.Id, static (ref global::Sample.Account t, string v) => Account_set_Id(t, v), isRequired: true),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Account, string>("Secret", "Secret", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Account t) => Account_get_Secret(t), static (ref global::Sample.Account t, string v) => t.Secret = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Account, string>("Hidden", "Hidden", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Account t) => Account_get_Hidden(t), static (ref global::Sample.Account t, string v) => Account_set_Hidden(t, v), isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Ambiguous>? _Sample_Ambiguous;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Ambiguous> Sample_Ambiguous => _Sample_Ambiguous ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Ambiguous>(
            create: null,
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Ambiguous>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Ambiguous, int>("A", "A", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Ambiguous t) => t.A, static (ref global::Sample.Ambiguous t, int v) => t.A = v, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.ByReference>? _Sample_ByReference;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.ByReference> Sample_ByReference => _Sample_ByReference ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.ByReference>(
            create: static args => { var a0 = (int)args[0]!; var a1 = (long)args[1]!; return new global::Sample.ByReference(ref a0, out a1); },
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("value", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<long>("limit", global::ValveKeyValue.Metadata.KVMetadata.Int64, defaultValue: default),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.ByReference>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.ByReference, int>("Value", "Value", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.ByReference t) => t.Value, setter: null, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Configured>? _Sample_Configured;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Configured> Sample_Configured => _Sample_Configured ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Configured>(
            create: static _ => new global::Sample.Configured(),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Configured>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Configured, string>("Name", "Name", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Configured t) => t.Name, static (ref global::Sample.Configured t, string v) => t.Name = v, isRequired: true),
            },
            constructorSetsRequiredMembers: true);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Counter>? _Sample_Counter;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Counter> Sample_Counter => _Sample_Counter ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Counter>(
            create: static _ => default(global::Sample.Counter),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Counter>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Counter, int>("Value", "Value", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Counter t) => t.Value, static (ref global::Sample.Counter t, int v) => Counter_set_Value(ref t, v), isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Factory>? _Sample_Factory;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Factory> Sample_Factory => _Sample_Factory ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Factory>(
            create: static args => Create_Factory((string)args[0]!, (global::Sample.Mode)args[1]!, (float)args[2]!, (string)args[3]!, (long)args[4]!, (short)args[5]!, (global::Sample.Size)args[6]!, (int?)args[7]!),
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<string>("name", global::ValveKeyValue.Metadata.KVMetadata.String, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<global::Sample.Mode>("mode", Sample_Mode, defaultValue: (global::Sample.Mode)(-1)),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<float>("scale", global::ValveKeyValue.Metadata.KVMetadata.Single, defaultValue: 0.5F),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<string>("label", global::ValveKeyValue.Metadata.KVMetadata.String, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<long>("limit", global::ValveKeyValue.Metadata.KVMetadata.Int64, defaultValue: 3L),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<short>("offset", global::ValveKeyValue.Metadata.KVMetadata.Int16, defaultValue: -2),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<global::Sample.Size>("size", Sample_Size, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int?>("count", int_4, defaultValue: 4),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Factory>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Factory, string>("Name", "Name", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Factory t) => t.Name, setter: null, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Mode>? _Sample_Mode;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Mode> Sample_Mode => _Sample_Mode ??= global::ValveKeyValue.Metadata.KVMetadata.Enum<global::Sample.Mode, int>(global::ValveKeyValue.Metadata.KVMetadata.Int32);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Outer<int>.Inner>? _Sample_Outer_1int_2_Inner;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Outer<int>.Inner> Sample_Outer_1int_2_Inner => _Sample_Outer_1int_2_Inner ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Outer<int>.Inner>(
            create: static _ => new global::Sample.Outer<int>.Inner(),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Outer<int>.Inner>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Outer<int>.Inner, int>("Value", "Value", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Outer<int>.Inner t) => t.Value, static (ref global::Sample.Outer<int>.Inner t, int v) => InnerAccessors<int>.Inner_set_Value(t, v), isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Pair<string>>? _Sample_Pair_1string_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Pair<string>> Sample_Pair_1string_2 => _Sample_Pair_1string_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Pair<string>>(
            create: static args => new global::Sample.Pair<string>((string)args[0]!, (string)args[1]!),
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<string>("First", global::ValveKeyValue.Metadata.KVMetadata.String, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<string>("Second", global::ValveKeyValue.Metadata.KVMetadata.String, defaultValue: default),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Pair<string>>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Pair<string>, string>("First", "First", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Pair<string> t) => t.First, static (ref global::Sample.Pair<string> t, string v) => PairAccessors<string>.Pair_String_set_First(t, v), isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Pair<string>, string>("Second", "Second", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Pair<string> t) => t.Second, static (ref global::Sample.Pair<string> t, string v) => PairAccessors<string>.Pair_String_set_Second(t, v), isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Point>? _Sample_Point;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Point> Sample_Point => _Sample_Point ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Point>(
            create: static args => new global::Sample.Point((int)args[0]!, (int)args[1]!, (int)args[2]!),
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("X", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("Y", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("Z", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: 7),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Point>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Point, int>("X", "X", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Point t) => t.X, static (ref global::Sample.Point t, int v) => Point_set_X(t, v), isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Point, int>("Y", "Y", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Point t) => t.Y, static (ref global::Sample.Point t, int v) => Point_set_Y(t, v), isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Point, int>("Z", "Z", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Point t) => t.Z, static (ref global::Sample.Point t, int v) => Point_set_Z(t, v), isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Size>? _Sample_Size;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Size> Sample_Size => _Sample_Size ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Size>(
            create: static args => new global::Sample.Size((int)args[0]!, (int)args[1]!),
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("width", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<int>("height", global::ValveKeyValue.Metadata.KVMetadata.Int32, defaultValue: default),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Size>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Size, int>("Width", "Width", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Size t) => t.Width, setter: null, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Size, int>("Height", "Height", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Size t) => t.Height, setter: null, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.SpanConstructor>? _Sample_SpanConstructor;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.SpanConstructor> Sample_SpanConstructor => _Sample_SpanConstructor ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.SpanConstructor>(
            create: static _ => throw new global::System.NotSupportedException("Constructor parameter 'name' of type 'ReadOnlySpan`1' on type 'SpanConstructor' is not supported."),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.SpanConstructor>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.SpanConstructor, string>("Name", "Name", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.SpanConstructor t) => t.Name, static (ref global::Sample.SpanConstructor t, string v) => t.Name = v, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.TwoMarked>? _Sample_TwoMarked;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.TwoMarked> Sample_TwoMarked => _Sample_TwoMarked ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.TwoMarked>(
            create: static _ => throw new global::ValveKeyValue.KeyValueException("Type 'TwoMarked' has more than one constructor marked with [KVConstructor]."),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.TwoMarked>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.TwoMarked, int>("A", "A", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.TwoMarked t) => t.A, static (ref global::Sample.TwoMarked t, int v) => t.A = v, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<global::Sample.Point, int>>? _System_Collections_Generic_Dictionary_1Sample_Point_3int_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<global::Sample.Point, int>> System_Collections_Generic_Dictionary_1Sample_Point_3int_2 => _System_Collections_Generic_Dictionary_1Sample_Point_3int_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Dictionary<global::System.Collections.Generic.Dictionary<global::Sample.Point, int>, global::Sample.Point, int>(Sample_Point, global::ValveKeyValue.Metadata.KVMetadata.Int32);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>>? _System_ValueTuple_1Sample_Size_3Sample_Counter_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>> System_ValueTuple_1Sample_Size_3Sample_Counter_2 => _System_ValueTuple_1Sample_Size_3Sample_Counter_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>>(
            create: static args => new global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>((global::Sample.Size)args[0]!, (global::Sample.Counter)args[1]!),
            parameters: static () => new global::ValveKeyValue.Metadata.KVParameterInfo[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<global::Sample.Size>("item1", Sample_Size, defaultValue: default),
                global::ValveKeyValue.Metadata.KVMetadata.Parameter<global::Sample.Counter>("item2", Sample_Counter, defaultValue: default),
            },
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>, global::Sample.Size>("Item1", "Item1", Sample_Size, static (global::System.ValueTuple<global::Sample.Size, global::Sample.Counter> t) => t.Item1, static (ref global::System.ValueTuple<global::Sample.Size, global::Sample.Counter> t, global::Sample.Size v) => t.Item1 = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::System.ValueTuple<global::Sample.Size, global::Sample.Counter>, global::Sample.Counter>("Item2", "Item2", Sample_Counter, static (global::System.ValueTuple<global::Sample.Size, global::Sample.Counter> t) => t.Item2, static (ref global::System.ValueTuple<global::Sample.Size, global::Sample.Counter> t, global::Sample.Counter v) => t.Item2 = v, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<int?>? _int_4;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<int?> int_4 => _int_4 ??= global::ValveKeyValue.Metadata.KVMetadata.Nullable<int>(global::ValveKeyValue.Metadata.KVMetadata.Int32);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Id")]
        static extern void Account_set_Id(global::Sample.Account target, string value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "get_Secret")]
        static extern string Account_get_Secret(global::Sample.Account target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "get_Hidden")]
        static extern string Account_get_Hidden(global::Sample.Account target);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Hidden")]
        static extern void Account_set_Hidden(global::Sample.Account target, string value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]
        static extern global::Sample.Account Create_Account();

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Value")]
        static extern void Counter_set_Value(ref global::Sample.Counter target, int value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]
        static extern global::Sample.Factory Create_Factory(string p0, global::Sample.Mode p1, float p2, string p3, in long p4, short p5, global::Sample.Size p6, int? p7);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_X")]
        static extern void Point_set_X(global::Sample.Point target, int value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Y")]
        static extern void Point_set_Y(global::Sample.Point target, int value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Z")]
        static extern void Point_set_Z(global::Sample.Point target, int value);

        static class InnerAccessors<T> where T : struct
        {
            [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Value")]
            public static extern void Inner_set_Value(global::Sample.Outer<T>.Inner target, T value);
        }

        static class PairAccessors<T> where T : class
        {
            [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_First")]
            public static extern void Pair_String_set_First(global::Sample.Pair<T> target, T value);

            [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Second")]
            public static extern void Pair_String_set_Second(global::Sample.Pair<T> target, T value);
        }
    }
}
