// <auto-generated/>
#nullable enable annotations
#nullable disable warnings
#pragma warning disable

namespace ValveKeyValue.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class KVGeneratedTypeInfo__For_Sample_DCF88FC7
    {
        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Child>? _Sample_Child;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Child> Sample_Child => _Sample_Child ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Child>(
            create: static _ => new global::Sample.Child(),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Child>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Child, double>("Weight", "Weight", global::ValveKeyValue.Metadata.KVMetadata.Double, static (global::Sample.Child t) => t.Weight, static (ref global::Sample.Child t, double v) => t.Weight = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Child, global::Sample.Child[]>("Nested", "Nested", Sample_Child_5_6, static (global::Sample.Child t) => t.Nested, static (ref global::Sample.Child t, global::Sample.Child[] v) => t.Nested = v, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Child[]>? _Sample_Child_5_6;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Child[]> Sample_Child_5_6 => _Sample_Child_5_6 ??= global::ValveKeyValue.Metadata.KVMetadata.Array<global::Sample.Child>(Sample_Child);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Color>? _Sample_Color;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Color> Sample_Color => _Sample_Color ??= global::ValveKeyValue.Metadata.KVMetadata.Enum<global::Sample.Color, byte>(global::ValveKeyValue.Metadata.KVMetadata.Byte);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Settings>? _Sample_Settings;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::Sample.Settings> Sample_Settings => _Sample_Settings ??= global::ValveKeyValue.Metadata.KVMetadata.Object<global::Sample.Settings>(
            create: static _ => new global::Sample.Settings(),
            parameters: null,
            members: static () => new global::ValveKeyValue.Metadata.KVMemberInfo<global::Sample.Settings>[]
            {
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, string>("Name", "Name", global::ValveKeyValue.Metadata.KVMetadata.String, static (global::Sample.Settings t) => t.Name, static (ref global::Sample.Settings t, string v) => t.Name = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, int>("max_count", "MaxCount", global::ValveKeyValue.Metadata.KVMetadata.Int32, static (global::Sample.Settings t) => t.MaxCount, static (ref global::Sample.Settings t, int v) => t.MaxCount = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, global::Sample.Color>("Color", "Color", Sample_Color, static (global::Sample.Settings t) => t.Color, static (ref global::Sample.Settings t, global::Sample.Color v) => t.Color = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, int?>("Optional", "Optional", int_4, static (global::Sample.Settings t) => t.Optional, static (ref global::Sample.Settings t, int? v) => t.Optional = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, global::System.Collections.Generic.List<string>>("Tags", "Tags", System_Collections_Generic_List_1string_2, static (global::Sample.Settings t) => t.Tags, static (ref global::Sample.Settings t, global::System.Collections.Generic.List<string> v) => t.Tags = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, global::System.Collections.Generic.Dictionary<int, global::Sample.Child>>("Children", "Children", System_Collections_Generic_Dictionary_1int_3Sample_Child_2, static (global::Sample.Settings t) => t.Children, static (ref global::Sample.Settings t, global::System.Collections.Generic.Dictionary<int, global::Sample.Child> v) => t.Children = v, isRequired: false),
                global::ValveKeyValue.Metadata.KVMetadata.Member<global::Sample.Settings, global::System.Collections.Generic.IEnumerable<int>>("Computed", "Computed", System_Collections_Generic_IEnumerable_1int_2, static (global::Sample.Settings t) => t.Computed, setter: null, isRequired: false),
            },
            constructorSetsRequiredMembers: false);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Sample.Child>>? _System_Collections_Generic_Dictionary_1int_3Sample_Child_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Sample.Child>> System_Collections_Generic_Dictionary_1int_3Sample_Child_2 => _System_Collections_Generic_Dictionary_1int_3Sample_Child_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Dictionary<global::System.Collections.Generic.Dictionary<int, global::Sample.Child>, int, global::Sample.Child>(global::ValveKeyValue.Metadata.KVMetadata.Int32, Sample_Child);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Sample.Settings>>? _System_Collections_Generic_Dictionary_1string_3Sample_Settings_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.Dictionary<string, global::Sample.Settings>> System_Collections_Generic_Dictionary_1string_3Sample_Settings_2 => _System_Collections_Generic_Dictionary_1string_3Sample_Settings_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Dictionary<global::System.Collections.Generic.Dictionary<string, global::Sample.Settings>, string, global::Sample.Settings>(global::ValveKeyValue.Metadata.KVMetadata.String, Sample_Settings);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.IEnumerable<int>>? _System_Collections_Generic_IEnumerable_1int_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.IEnumerable<int>> System_Collections_Generic_IEnumerable_1int_2 => _System_Collections_Generic_IEnumerable_1int_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Collection<global::System.Collections.Generic.IEnumerable<int>, int>(global::ValveKeyValue.Metadata.KVMetadata.Int32);

        static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.List<string>>? _System_Collections_Generic_List_1string_2;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<global::System.Collections.Generic.List<string>> System_Collections_Generic_List_1string_2 => _System_Collections_Generic_List_1string_2 ??= global::ValveKeyValue.Metadata.KVMetadata.Collection<global::System.Collections.Generic.List<string>, string>(global::ValveKeyValue.Metadata.KVMetadata.String);

        static global::ValveKeyValue.Metadata.KVTypeInfo<int?>? _int_4;

        internal static global::ValveKeyValue.Metadata.KVTypeInfo<int?> int_4 => _int_4 ??= global::ValveKeyValue.Metadata.KVMetadata.Nullable<int>(global::ValveKeyValue.Metadata.KVMetadata.Int32);
    }
}
