// <auto-generated/>
#nullable enable annotations
#nullable disable warnings
#pragma warning disable

namespace System.Runtime.CompilerServices
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace ValveKeyValue.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("ValveKeyValue.SourceGenerator", "VERSION")]
    file static class KVSerializerInterceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4VsYDAABQcm9ncmFtLmNz")] // Program.cs(45,55)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4ViwEAABQcm9ncmFtLmNz")] // Program.cs(47,60)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4VqIFAABQcm9ncmFtLmNz")] // Program.cs(53,64)
        public static global::Sample.Settings Deserialize_Sample_Settings(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::Sample.Settings>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Settings, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4ViQFAABQcm9ncmFtLmNz")] // Program.cs(51,78)
        public static global::System.Collections.Generic.Dictionary<string, global::Sample.Settings> Deserialize_System_Collections_Generic_Dictionary_1string_3Sample_Settings_2(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<global::System.Collections.Generic.Dictionary<string, global::Sample.Settings>>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.System_Collections_Generic_Dictionary_1string_3Sample_Settings_2, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4VooGAABQcm9ncmFtLmNz")] // Program.cs(57,68)
        public static int? Deserialize_int_4(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Deserialize<int?>(stream, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.int_4, options);

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4VqIEAABQcm9ncmFtLmNz")] // Program.cs(49,70)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "xPb6PJjlEAzCcIecswi4VhwGAABQcm9ncmFtLmNz")] // Program.cs(55,79)
        public static void Serialize_Sample_Settings(this global::ValveKeyValue.KVSerializer serializer, global::System.IO.Stream stream, global::Sample.Settings data, string name, global::ValveKeyValue.KVSerializerOptions? options = null)
            => serializer.Serialize<global::Sample.Settings>(stream, data, name, global::ValveKeyValue.Generated.KVGeneratedTypeInfo__For_Sample_DCF88FC7.Sample_Settings, options);
    }
}
