using System.Text;

namespace ValveKeyValue.SourceGenerator
{
    // Writes indented lines of source code with '\n' line endings.
    sealed class CodeWriter
    {
        public const string Header = "// <auto-generated/>\n#nullable enable annotations\n#nullable disable warnings\n#pragma warning disable\n";

        public static readonly string GeneratedCodeAttribute = $"[global::System.CodeDom.Compiler.GeneratedCode(\"ValveKeyValue.SourceGenerator\", \"{typeof(CodeWriter).Assembly.GetName().Version?.ToString() ?? "0.0.0.0"}\")]";

        readonly StringBuilder sb = new();
        int indentation;

        public void Indent() => indentation++;

        public void Unindent() => indentation--;

        public void OpenBlock()
        {
            WriteLine("{");
            indentation++;
        }

        public void CloseBlock(string suffix = "")
        {
            indentation--;
            WriteLine("}" + suffix);
        }

        public void WriteLine()
        {
            sb.Append('\n');
        }

        public void WriteLine(string line)
        {
            sb.Append(' ', indentation * 4);
            sb.Append(line);
            sb.Append('\n');
        }

        public void WriteLines(string lines)
        {
            foreach (var line in lines.Split('\n'))
            {
                WriteLine(line);
            }
        }

        public override string ToString() => sb.ToString();
    }
}
